name: Feature Request
description: Suggest a new feature or improvement
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

        **Note:** Before submitting, please check existing issues to avoid duplicates.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: What problem does this feature solve? Why do you need it?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature or change you'd like to see.
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried...

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the app does this relate to?
      options:
        - Expenses
        - Participants
        - Balances / Settlements
        - Groups (Parties)
        - Sync / Offline
        - Mobile App
        - UI / Design
        - Accessibility
        - Internationalization
        - Other
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If you have any mockups, screenshots of similar features in other apps, or examples, add them here.
      placeholder: Drag and drop images here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or details about the feature request.
      placeholder: Add any other context...

