import { defineConfig, Plugin } from "vite";
import react from "@vitejs/plugin-react";
import { TanStackRouterVite } from "@tanstack/router-plugin/vite";
import wasm from "vite-plugin-wasm";
import topLevelAwait from "vite-plugin-top-level-await";
import { lingui } from "@lingui/vite-plugin";

const ReactCompilerConfig = {};

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    TanStackRouterVite(),
    react({
      babel: {
        plugins: [
          "babel-plugin-macros",
          ["babel-plugin-react-compiler", ReactCompilerConfig],
        ],
      },
    }),
    wasm(),
    topLevelAwait(),
    lingui(),
    preloadIconsPlugin({
      matchers: [/#lucide\/([^"'`]+)/g],
      importPreloadFunction: `import { preloadIcon } from "#src/ui/Icon.js";`,
      preloadFunctionName: "preloadIcon",
    }),
  ],
});

interface PreloadIconsPluginOptions {
  matchers: RegExp[];
  importPreloadFunction: string;
  preloadFunctionName: string;

  /**
   * @default "src/preloadIcons.gen.ts"
   */
  outFile?: string;
}

function preloadIconsPlugin({
  matchers,
  importPreloadFunction,
  preloadFunctionName,
  outFile = "src/preloadIcons.gen.ts",
}: PreloadIconsPluginOptions): Plugin {
  const matches = new Set<string>();
  const compile = debounce(writeFile, 1000);

  function debounce(fn: () => void, ms: number) {
    let timeout: NodeJS.Timeout;

    return () => {
      clearTimeout(timeout);
      timeout = setTimeout(fn, ms);
    };
  }

  async function writeFile() {
    const code = `/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router

${importPreloadFunction}

export function preloadAllIcons() {
  return Promise.all([
    ${Array.from(matches)
      .map((match) => `${preloadFunctionName}("${match}")`)
      .join(",\n")}
  ])
}
  
/* prettier-ignore-end */`;

    const fs = await import("node:fs/promises");

    await fs.writeFile(outFile, code, "utf-8");
  }

  return {
    name: "vite-plugin-preload-icons",

    async transform(code, id) {
      const scanForIcons = id.includes(".ts") || id.includes(".tsx");

      if (id.includes(outFile) || !scanForIcons) {
        return;
      }

      for (const matcher of matchers) {
        const regexResult = code.match(matcher);

        if (regexResult) {
          regexResult.forEach((match) => {
            matches.add(match);
          });

          compile();
        }
      }
    },
  };
}
