import { defineConfig, Plugin } from "vite";
import react from "@vitejs/plugin-react";
import { TanStackRouterVite } from "@tanstack/router-plugin/vite";
import wasm from "vite-plugin-wasm";
import topLevelAwait from "vite-plugin-top-level-await";
import { lingui } from "@lingui/vite-plugin";
import { VitePWA } from "vite-plugin-pwa";

const ReactCompilerConfig = {};

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    TanStackRouterVite(),
    react({
      babel: {
        plugins: [
          "babel-plugin-macros",
          ["babel-plugin-react-compiler", ReactCompilerConfig],
        ],
      },
    }),
    wasm(),
    topLevelAwait(),
    lingui(),
    preloadIconsPlugin({
      matchers: [/#lucide\/([^"'`]+)/g],
      importPreloadFunction: `import { preloadIcon } from "#src/ui/Icon.js";`,
      preloadFunctionName: "preloadIcon",
    }),
    VitePWA({
      registerType: "prompt",
      workbox: {
        maximumFileSizeToCacheInBytes: 5242880,
      },
      manifest: {
        name: "trizum",
        short_name: "trizum",
        description: "Split your bills with friends",
        theme_color: "#000000",
        background_color: "#000000",
        display: "standalone",
        icons: [
          {
            src: "maskable-icon-512x512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
          {
            src: "pwa-64x64.png",
            sizes: "64x64",
            type: "image/png",
          },
          {
            src: "pwa-192x192.png",
            sizes: "192x192",
            type: "image/png",
          },
          {
            src: "pwa-512x512.png",
            sizes: "512x512",
            type: "image/png",
          },
        ],
      },
    }),
  ],
  server: {
    proxy: {
      "/api": {
        target: "http://localhost:8788",
        changeOrigin: true,
      },
    },
  },
});

interface PreloadIconsPluginOptions {
  matchers: RegExp[];
  importPreloadFunction: string;
  preloadFunctionName: string;

  /**
   * @default "src/preloadIcons.gen.ts"
   */
  outFile?: string;
}

function preloadIconsPlugin({
  matchers,
  importPreloadFunction,
  preloadFunctionName,
  outFile = "src/preloadIcons.gen.ts",
}: PreloadIconsPluginOptions): Plugin {
  const matches = new Set<string>();
  const compile = debounce(writeFile, 1000);

  function debounce(fn: () => void, ms: number) {
    let timeout: NodeJS.Timeout;

    return () => {
      clearTimeout(timeout);
      timeout = setTimeout(fn, ms);
    };
  }

  let prev = "";

  async function writeFile() {
    const sorted = Array.from(matches).sort();
    const joined = sorted.join();

    if (prev === joined) {
      return;
    }

    prev = joined;

    const code = `/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by vite-plugin-preload-icons

${importPreloadFunction}

export function preloadAllIcons() {
  return Promise.all([
    ${sorted.map((match) => `${preloadFunctionName}("${match}")`).join(",\n")}
  ])
}
  
/* prettier-ignore-end */`;

    const fs = await import("node:fs/promises");

    await fs.writeFile(outFile, code, "utf-8");
  }

  let isDev = false;

  return {
    name: "vite-plugin-preload-icons",

    configResolved(config) {
      isDev = config.command !== "build";
    },

    async transform(code, id) {
      if (!isDev) {
        return;
      }

      const scanForIcons = id.includes(".ts") || id.includes(".tsx");

      if (id.includes(outFile) || !scanForIcons) {
        return;
      }

      for (const matcher of matchers) {
        const regexResult = code.match(matcher);

        if (regexResult) {
          regexResult.forEach((match) => {
            matches.add(match);
          });

          compile();
        }
      }
    },
  };
}
