/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by vite-plugin-preload-icons

import { preloadIcon } from "#src/ui/Icon.js";

export function preloadAllIcons() {
  return Promise.all([
    preloadIcon("#lucide/ampersand"),
preloadIcon("#lucide/archive"),
preloadIcon("#lucide/archive-restore"),
preloadIcon("#lucide/arrow-left"),
preloadIcon("#lucide/arrow-right"),
preloadIcon("#lucide/badge-info"),
preloadIcon("#lucide/calendar"),
preloadIcon("#lucide/camera"),
preloadIcon("#lucide/check"),
preloadIcon("#lucide/chevron-down"),
preloadIcon("#lucide/chevron-left"),
preloadIcon("#lucide/chevron-right"),
preloadIcon("#lucide/circle"),
preloadIcon("#lucide/circle-alert"),
preloadIcon("#lucide/circle-arrow-down"),
preloadIcon("#lucide/circle-check"),
preloadIcon("#lucide/circle-help"),
preloadIcon("#lucide/copy"),
preloadIcon("#lucide/ellipsis-vertical"),
preloadIcon("#lucide/image"),
preloadIcon("#lucide/image-up"),
preloadIcon("#lucide/images"),
preloadIcon("#lucide/import"),
preloadIcon("#lucide/info"),
preloadIcon("#lucide/list-plus"),
preloadIcon("#lucide/log-out"),
preloadIcon("#lucide/minus"),
preloadIcon("#lucide/pencil"),
preloadIcon("#lucide/plus"),
preloadIcon("#lucide/refresh-cw"),
preloadIcon("#lucide/scale"),
preloadIcon("#lucide/scroll-text"),
preloadIcon("#lucide/settings"),
preloadIcon("#lucide/share"),
preloadIcon("#lucide/split"),
preloadIcon("#lucide/test-tube-diagonal"),
preloadIcon("#lucide/trash"),
preloadIcon("#lucide/user"),
preloadIcon("#lucide/user-round-check"),
preloadIcon("#lucide/user-round-pen"),
preloadIcon("#lucide/users"),
preloadIcon("#lucide/x")
  ])
}
  
/* prettier-ignore-end */