/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router

import { preloadIcon } from "#src/ui/Icon.js";

export function preloadAllIcons() {
  return Promise.all([
    preloadIcon("#lucide/check"),
preloadIcon("#lucide/trash"),
preloadIcon("#lucide/plus"),
preloadIcon("#lucide/ellipsis-vertical"),
preloadIcon("#lucide/settings"),
preloadIcon("#lucide/info"),
preloadIcon("#lucide/ampersand"),
preloadIcon("#lucide/list-plus"),
preloadIcon("#lucide/user-round-pen"),
preloadIcon("#lucide/log-out"),
preloadIcon("#lucide/circle-check"),
preloadIcon("#lucide/circle"),
preloadIcon("#lucide/archive"),
preloadIcon("#lucide/archive-restore"),
preloadIcon("#lucide/arrow-left")
  ])
}
  
/* prettier-ignore-end */