/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as NewRouteImport } from './routes/new'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartyPartyIdRouteImport } from './routes/party.$partyId'
import { Route as MigrateTricountRouteImport } from './routes/migrate_.tricount'
import { Route as AboutThirdPartyLicensesRouteImport } from './routes/about_.third-party-licenses'
import { Route as PartyPartyIdWhoRouteImport } from './routes/party_.$partyId.who'
import { Route as PartyPartyIdShareRouteImport } from './routes/party_.$partyId.share'
import { Route as PartyPartyIdSettingsRouteImport } from './routes/party_.$partyId.settings'
import { Route as PartyPartyIdPayRouteImport } from './routes/party_.$partyId.pay'
import { Route as PartyPartyIdAddRouteImport } from './routes/party_.$partyId.add'
import { Route as PartyPartyIdExpenseExpenseIdRouteImport } from './routes/party_.$partyId.expense.$expenseId'
import { Route as PartyPartyIdExpenseExpenseIdEditRouteImport } from './routes/party_.$partyId.expense.$expenseId_.edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyPartyIdRoute = PartyPartyIdRouteImport.update({
  id: '/party/$partyId',
  path: '/party/$partyId',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrateTricountRoute = MigrateTricountRouteImport.update({
  id: '/migrate_/tricount',
  path: '/migrate/tricount',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutThirdPartyLicensesRoute = AboutThirdPartyLicensesRouteImport.update({
  id: '/about_/third-party-licenses',
  path: '/about/third-party-licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyPartyIdWhoRoute = PartyPartyIdWhoRouteImport.update({
  id: '/party_/$partyId/who',
  path: '/party/$partyId/who',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyPartyIdShareRoute = PartyPartyIdShareRouteImport.update({
  id: '/party_/$partyId/share',
  path: '/party/$partyId/share',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyPartyIdSettingsRoute = PartyPartyIdSettingsRouteImport.update({
  id: '/party_/$partyId/settings',
  path: '/party/$partyId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyPartyIdPayRoute = PartyPartyIdPayRouteImport.update({
  id: '/party_/$partyId/pay',
  path: '/party/$partyId/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyPartyIdAddRoute = PartyPartyIdAddRouteImport.update({
  id: '/party_/$partyId/add',
  path: '/party/$partyId/add',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyPartyIdExpenseExpenseIdRoute =
  PartyPartyIdExpenseExpenseIdRouteImport.update({
    id: '/party_/$partyId/expense/$expenseId',
    path: '/party/$partyId/expense/$expenseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PartyPartyIdExpenseExpenseIdEditRoute =
  PartyPartyIdExpenseExpenseIdEditRouteImport.update({
    id: '/party_/$partyId/expense/$expenseId_/edit',
    path: '/party/$partyId/expense/$expenseId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/join': typeof JoinRoute
  '/new': typeof NewRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/settings': typeof SettingsRoute
  '/about/third-party-licenses': typeof AboutThirdPartyLicensesRoute
  '/migrate/tricount': typeof MigrateTricountRoute
  '/party/$partyId': typeof PartyPartyIdRoute
  '/party/$partyId/add': typeof PartyPartyIdAddRoute
  '/party/$partyId/pay': typeof PartyPartyIdPayRoute
  '/party/$partyId/settings': typeof PartyPartyIdSettingsRoute
  '/party/$partyId/share': typeof PartyPartyIdShareRoute
  '/party/$partyId/who': typeof PartyPartyIdWhoRoute
  '/party/$partyId/expense/$expenseId': typeof PartyPartyIdExpenseExpenseIdRoute
  '/party/$partyId/expense/$expenseId/edit': typeof PartyPartyIdExpenseExpenseIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/join': typeof JoinRoute
  '/new': typeof NewRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/settings': typeof SettingsRoute
  '/about/third-party-licenses': typeof AboutThirdPartyLicensesRoute
  '/migrate/tricount': typeof MigrateTricountRoute
  '/party/$partyId': typeof PartyPartyIdRoute
  '/party/$partyId/add': typeof PartyPartyIdAddRoute
  '/party/$partyId/pay': typeof PartyPartyIdPayRoute
  '/party/$partyId/settings': typeof PartyPartyIdSettingsRoute
  '/party/$partyId/share': typeof PartyPartyIdShareRoute
  '/party/$partyId/who': typeof PartyPartyIdWhoRoute
  '/party/$partyId/expense/$expenseId': typeof PartyPartyIdExpenseExpenseIdRoute
  '/party/$partyId/expense/$expenseId/edit': typeof PartyPartyIdExpenseExpenseIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/join': typeof JoinRoute
  '/new': typeof NewRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/settings': typeof SettingsRoute
  '/about_/third-party-licenses': typeof AboutThirdPartyLicensesRoute
  '/migrate_/tricount': typeof MigrateTricountRoute
  '/party/$partyId': typeof PartyPartyIdRoute
  '/party_/$partyId/add': typeof PartyPartyIdAddRoute
  '/party_/$partyId/pay': typeof PartyPartyIdPayRoute
  '/party_/$partyId/settings': typeof PartyPartyIdSettingsRoute
  '/party_/$partyId/share': typeof PartyPartyIdShareRoute
  '/party_/$partyId/who': typeof PartyPartyIdWhoRoute
  '/party_/$partyId/expense/$expenseId': typeof PartyPartyIdExpenseExpenseIdRoute
  '/party_/$partyId/expense/$expenseId_/edit': typeof PartyPartyIdExpenseExpenseIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/join'
    | '/new'
    | '/privacy-policy'
    | '/settings'
    | '/about/third-party-licenses'
    | '/migrate/tricount'
    | '/party/$partyId'
    | '/party/$partyId/add'
    | '/party/$partyId/pay'
    | '/party/$partyId/settings'
    | '/party/$partyId/share'
    | '/party/$partyId/who'
    | '/party/$partyId/expense/$expenseId'
    | '/party/$partyId/expense/$expenseId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/join'
    | '/new'
    | '/privacy-policy'
    | '/settings'
    | '/about/third-party-licenses'
    | '/migrate/tricount'
    | '/party/$partyId'
    | '/party/$partyId/add'
    | '/party/$partyId/pay'
    | '/party/$partyId/settings'
    | '/party/$partyId/share'
    | '/party/$partyId/who'
    | '/party/$partyId/expense/$expenseId'
    | '/party/$partyId/expense/$expenseId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/join'
    | '/new'
    | '/privacy-policy'
    | '/settings'
    | '/about_/third-party-licenses'
    | '/migrate_/tricount'
    | '/party/$partyId'
    | '/party_/$partyId/add'
    | '/party_/$partyId/pay'
    | '/party_/$partyId/settings'
    | '/party_/$partyId/share'
    | '/party_/$partyId/who'
    | '/party_/$partyId/expense/$expenseId'
    | '/party_/$partyId/expense/$expenseId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  JoinRoute: typeof JoinRoute
  NewRoute: typeof NewRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SettingsRoute: typeof SettingsRoute
  AboutThirdPartyLicensesRoute: typeof AboutThirdPartyLicensesRoute
  MigrateTricountRoute: typeof MigrateTricountRoute
  PartyPartyIdRoute: typeof PartyPartyIdRoute
  PartyPartyIdAddRoute: typeof PartyPartyIdAddRoute
  PartyPartyIdPayRoute: typeof PartyPartyIdPayRoute
  PartyPartyIdSettingsRoute: typeof PartyPartyIdSettingsRoute
  PartyPartyIdShareRoute: typeof PartyPartyIdShareRoute
  PartyPartyIdWhoRoute: typeof PartyPartyIdWhoRoute
  PartyPartyIdExpenseExpenseIdRoute: typeof PartyPartyIdExpenseExpenseIdRoute
  PartyPartyIdExpenseExpenseIdEditRoute: typeof PartyPartyIdExpenseExpenseIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/$partyId': {
      id: '/party/$partyId'
      path: '/party/$partyId'
      fullPath: '/party/$partyId'
      preLoaderRoute: typeof PartyPartyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrate_/tricount': {
      id: '/migrate_/tricount'
      path: '/migrate/tricount'
      fullPath: '/migrate/tricount'
      preLoaderRoute: typeof MigrateTricountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/third-party-licenses': {
      id: '/about_/third-party-licenses'
      path: '/about/third-party-licenses'
      fullPath: '/about/third-party-licenses'
      preLoaderRoute: typeof AboutThirdPartyLicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party_/$partyId/who': {
      id: '/party_/$partyId/who'
      path: '/party/$partyId/who'
      fullPath: '/party/$partyId/who'
      preLoaderRoute: typeof PartyPartyIdWhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party_/$partyId/share': {
      id: '/party_/$partyId/share'
      path: '/party/$partyId/share'
      fullPath: '/party/$partyId/share'
      preLoaderRoute: typeof PartyPartyIdShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party_/$partyId/settings': {
      id: '/party_/$partyId/settings'
      path: '/party/$partyId/settings'
      fullPath: '/party/$partyId/settings'
      preLoaderRoute: typeof PartyPartyIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party_/$partyId/pay': {
      id: '/party_/$partyId/pay'
      path: '/party/$partyId/pay'
      fullPath: '/party/$partyId/pay'
      preLoaderRoute: typeof PartyPartyIdPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party_/$partyId/add': {
      id: '/party_/$partyId/add'
      path: '/party/$partyId/add'
      fullPath: '/party/$partyId/add'
      preLoaderRoute: typeof PartyPartyIdAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party_/$partyId/expense/$expenseId': {
      id: '/party_/$partyId/expense/$expenseId'
      path: '/party/$partyId/expense/$expenseId'
      fullPath: '/party/$partyId/expense/$expenseId'
      preLoaderRoute: typeof PartyPartyIdExpenseExpenseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party_/$partyId/expense/$expenseId_/edit': {
      id: '/party_/$partyId/expense/$expenseId_/edit'
      path: '/party/$partyId/expense/$expenseId/edit'
      fullPath: '/party/$partyId/expense/$expenseId/edit'
      preLoaderRoute: typeof PartyPartyIdExpenseExpenseIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  JoinRoute: JoinRoute,
  NewRoute: NewRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SettingsRoute: SettingsRoute,
  AboutThirdPartyLicensesRoute: AboutThirdPartyLicensesRoute,
  MigrateTricountRoute: MigrateTricountRoute,
  PartyPartyIdRoute: PartyPartyIdRoute,
  PartyPartyIdAddRoute: PartyPartyIdAddRoute,
  PartyPartyIdPayRoute: PartyPartyIdPayRoute,
  PartyPartyIdSettingsRoute: PartyPartyIdSettingsRoute,
  PartyPartyIdShareRoute: PartyPartyIdShareRoute,
  PartyPartyIdWhoRoute: PartyPartyIdWhoRoute,
  PartyPartyIdExpenseExpenseIdRoute: PartyPartyIdExpenseExpenseIdRoute,
  PartyPartyIdExpenseExpenseIdEditRoute: PartyPartyIdExpenseExpenseIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
