/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as NewImport } from './routes/new'
import { Route as JoinImport } from './routes/join'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as PartyPartyIdImport } from './routes/party.$partyId'
import { Route as PartyPartyIdSettingsImport } from './routes/party_.$partyId.settings'
import { Route as PartyPartyIdAddImport } from './routes/party_.$partyId.add'
import { Route as PartyPartyIdExpenseExpenseIdImport } from './routes/party_.$partyId.expense.$expenseId'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const NewRoute = NewImport.update({
  path: '/new',
  getParentRoute: () => rootRoute,
} as any)

const JoinRoute = JoinImport.update({
  path: '/join',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PartyPartyIdRoute = PartyPartyIdImport.update({
  path: '/party/$partyId',
  getParentRoute: () => rootRoute,
} as any)

const PartyPartyIdSettingsRoute = PartyPartyIdSettingsImport.update({
  path: '/party/$partyId/settings',
  getParentRoute: () => rootRoute,
} as any)

const PartyPartyIdAddRoute = PartyPartyIdAddImport.update({
  path: '/party/$partyId/add',
  getParentRoute: () => rootRoute,
} as any)

const PartyPartyIdExpenseExpenseIdRoute =
  PartyPartyIdExpenseExpenseIdImport.update({
    path: '/party/$partyId/expense/$expenseId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinImport
      parentRoute: typeof rootRoute
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/party/$partyId': {
      id: '/party/$partyId'
      path: '/party/$partyId'
      fullPath: '/party/$partyId'
      preLoaderRoute: typeof PartyPartyIdImport
      parentRoute: typeof rootRoute
    }
    '/party/$partyId/add': {
      id: '/party/$partyId/add'
      path: '/party/$partyId/add'
      fullPath: '/party/$partyId/add'
      preLoaderRoute: typeof PartyPartyIdAddImport
      parentRoute: typeof rootRoute
    }
    '/party/$partyId/settings': {
      id: '/party/$partyId/settings'
      path: '/party/$partyId/settings'
      fullPath: '/party/$partyId/settings'
      preLoaderRoute: typeof PartyPartyIdSettingsImport
      parentRoute: typeof rootRoute
    }
    '/party/$partyId/expense/$expenseId': {
      id: '/party/$partyId/expense/$expenseId'
      path: '/party/$partyId/expense/$expenseId'
      fullPath: '/party/$partyId/expense/$expenseId'
      preLoaderRoute: typeof PartyPartyIdExpenseExpenseIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AboutRoute,
  JoinRoute,
  NewRoute,
  SettingsRoute,
  PartyPartyIdRoute,
  PartyPartyIdAddRoute,
  PartyPartyIdSettingsRoute,
  PartyPartyIdExpenseExpenseIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/join",
        "/new",
        "/settings",
        "/party/$partyId",
        "/party/$partyId/add",
        "/party/$partyId/settings",
        "/party/$partyId/expense/$expenseId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/join": {
      "filePath": "join.tsx"
    },
    "/new": {
      "filePath": "new.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/party/$partyId": {
      "filePath": "party.$partyId.tsx"
    },
    "/party/$partyId/add": {
      "filePath": "party_.$partyId.add.tsx"
    },
    "/party/$partyId/settings": {
      "filePath": "party_.$partyId.settings.tsx"
    },
    "/party/$partyId/expense/$expenseId": {
      "filePath": "party_.$partyId.expense.$expenseId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
