/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NewRouteImport } from './routes/new'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartyPartyIdRouteImport } from './routes/party.$partyId'
import { Route as PartyPartyIdWhoRouteImport } from './routes/party_.$partyId.who'
import { Route as PartyPartyIdSettingsRouteImport } from './routes/party_.$partyId.settings'
import { Route as PartyPartyIdAddRouteImport } from './routes/party_.$partyId.add'
import { Route as PartyPartyIdExpenseExpenseIdRouteImport } from './routes/party_.$partyId.expense.$expenseId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyPartyIdRoute = PartyPartyIdRouteImport.update({
  id: '/party/$partyId',
  path: '/party/$partyId',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyPartyIdWhoRoute = PartyPartyIdWhoRouteImport.update({
  id: '/party_/$partyId/who',
  path: '/party/$partyId/who',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyPartyIdSettingsRoute = PartyPartyIdSettingsRouteImport.update({
  id: '/party_/$partyId/settings',
  path: '/party/$partyId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyPartyIdAddRoute = PartyPartyIdAddRouteImport.update({
  id: '/party_/$partyId/add',
  path: '/party/$partyId/add',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyPartyIdExpenseExpenseIdRoute =
  PartyPartyIdExpenseExpenseIdRouteImport.update({
    id: '/party_/$partyId/expense/$expenseId',
    path: '/party/$partyId/expense/$expenseId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/join': typeof JoinRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/party/$partyId': typeof PartyPartyIdRoute
  '/party/$partyId/add': typeof PartyPartyIdAddRoute
  '/party/$partyId/settings': typeof PartyPartyIdSettingsRoute
  '/party/$partyId/who': typeof PartyPartyIdWhoRoute
  '/party/$partyId/expense/$expenseId': typeof PartyPartyIdExpenseExpenseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/join': typeof JoinRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/party/$partyId': typeof PartyPartyIdRoute
  '/party/$partyId/add': typeof PartyPartyIdAddRoute
  '/party/$partyId/settings': typeof PartyPartyIdSettingsRoute
  '/party/$partyId/who': typeof PartyPartyIdWhoRoute
  '/party/$partyId/expense/$expenseId': typeof PartyPartyIdExpenseExpenseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/join': typeof JoinRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/party/$partyId': typeof PartyPartyIdRoute
  '/party_/$partyId/add': typeof PartyPartyIdAddRoute
  '/party_/$partyId/settings': typeof PartyPartyIdSettingsRoute
  '/party_/$partyId/who': typeof PartyPartyIdWhoRoute
  '/party_/$partyId/expense/$expenseId': typeof PartyPartyIdExpenseExpenseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/join'
    | '/new'
    | '/settings'
    | '/party/$partyId'
    | '/party/$partyId/add'
    | '/party/$partyId/settings'
    | '/party/$partyId/who'
    | '/party/$partyId/expense/$expenseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/join'
    | '/new'
    | '/settings'
    | '/party/$partyId'
    | '/party/$partyId/add'
    | '/party/$partyId/settings'
    | '/party/$partyId/who'
    | '/party/$partyId/expense/$expenseId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/join'
    | '/new'
    | '/settings'
    | '/party/$partyId'
    | '/party_/$partyId/add'
    | '/party_/$partyId/settings'
    | '/party_/$partyId/who'
    | '/party_/$partyId/expense/$expenseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  JoinRoute: typeof JoinRoute
  NewRoute: typeof NewRoute
  SettingsRoute: typeof SettingsRoute
  PartyPartyIdRoute: typeof PartyPartyIdRoute
  PartyPartyIdAddRoute: typeof PartyPartyIdAddRoute
  PartyPartyIdSettingsRoute: typeof PartyPartyIdSettingsRoute
  PartyPartyIdWhoRoute: typeof PartyPartyIdWhoRoute
  PartyPartyIdExpenseExpenseIdRoute: typeof PartyPartyIdExpenseExpenseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/$partyId': {
      id: '/party/$partyId'
      path: '/party/$partyId'
      fullPath: '/party/$partyId'
      preLoaderRoute: typeof PartyPartyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party_/$partyId/who': {
      id: '/party_/$partyId/who'
      path: '/party/$partyId/who'
      fullPath: '/party/$partyId/who'
      preLoaderRoute: typeof PartyPartyIdWhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party_/$partyId/settings': {
      id: '/party_/$partyId/settings'
      path: '/party/$partyId/settings'
      fullPath: '/party/$partyId/settings'
      preLoaderRoute: typeof PartyPartyIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party_/$partyId/add': {
      id: '/party_/$partyId/add'
      path: '/party/$partyId/add'
      fullPath: '/party/$partyId/add'
      preLoaderRoute: typeof PartyPartyIdAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party_/$partyId/expense/$expenseId': {
      id: '/party_/$partyId/expense/$expenseId'
      path: '/party/$partyId/expense/$expenseId'
      fullPath: '/party/$partyId/expense/$expenseId'
      preLoaderRoute: typeof PartyPartyIdExpenseExpenseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  JoinRoute: JoinRoute,
  NewRoute: NewRoute,
  SettingsRoute: SettingsRoute,
  PartyPartyIdRoute: PartyPartyIdRoute,
  PartyPartyIdAddRoute: PartyPartyIdAddRoute,
  PartyPartyIdSettingsRoute: PartyPartyIdSettingsRoute,
  PartyPartyIdWhoRoute: PartyPartyIdWhoRoute,
  PartyPartyIdExpenseExpenseIdRoute: PartyPartyIdExpenseExpenseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
